version: '3.8'

services:
  catalog.api:
    container_name: lde.catalog.api
    build:
      context: .
      dockerfile: Catalog/Catalog.Host/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - postgres
    ports:
      - 5000:5000
    networks:
      - default

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - catalog.api
    networks:
      - default

networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.4/24
          gateway: 192.168.0.4
